import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public class inicio extends javax.swing.JFrame {

    private static Connection con;
    // Declaramos los datos de conexion a la bd
    private static final String driver="com.mysql.jdbc.Driver";
    private static final String user="root";
    private static final String pass="";
    private static final String url="jdbc:mysql://localhost:3306/punto_de_venta";
    PreparedStatement ps;
    ResultSet rs;
    
    // Funcion que va conectarse a mi bd de mysql
    public static Connection getConnection() {
        // Reseteamos a null la conexion a la bd
        Connection con=null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            // Nos conectamos a la bd
            con= (Connection) DriverManager.getConnection(url, user, pass);
            JOptionPane.showMessageDialog(null, "conexion exitosa");
        }
        // Si la conexion NO fue exitosa mostramos un mensaje de error
        catch (HeadlessException | ClassNotFoundException | SQLException e){
            System.out.println(e);
        }
        return con;
    }
    private void limpiar() {
        txtIContrasena.setText(null);

    }
    public inicio() {   
        initComponents();
        setLocationRelativeTo(null);
        txtITipo.setVisible(false);
        
    }
    public void Validar() {
        if (txtINombre.getText().isEmpty()) {
            //coloca el texto en el label del campo obligatorio
            lblIANombre.setText("*campo requerido");
        }else{
            //deja de mostrar el mensaje
            lblIANombre.setText("");
        } 
        if (txtIContrasena.getText().isEmpty()) {
            //coloca el texto en el label del campo obligatorio
            lblIAContrasena.setText("*campo requerido");
        }else{
            //deja de mostrar el mensaje
            lblIAContrasena.setText("");
        }
        if (txtINombre.getText().isEmpty() || txtIContrasena.getText().isEmpty()){
            btnIInicio.setEnabled(false);
        }else {
            btnIInicio.setEnabled(true);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIInicio = new javax.swing.JLabel();
        lblINombre = new javax.swing.JLabel();
        lblIContraseña = new javax.swing.JLabel();
        txtINombre = new javax.swing.JTextField();
        btnIInicio = new javax.swing.JButton();
        lblIANombre = new javax.swing.JLabel();
        lblIAContrasena = new javax.swing.JLabel();
        txtIContrasena = new javax.swing.JPasswordField();
        txtITipo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblIInicio.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblIInicio.setText("inicio de sesion");

        lblINombre.setText("Nombre:");

        lblIContraseña.setText("Contraseña:");

        txtINombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtINombreActionPerformed(evt);
            }
        });
        txtINombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtINombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtINombreKeyTyped(evt);
            }
        });

        btnIInicio.setText("iniciar sesion");
        btnIInicio.setEnabled(false);
        btnIInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIInicioActionPerformed(evt);
            }
        });

        lblIANombre.setForeground(new java.awt.Color(255, 51, 51));
        lblIANombre.setText(" ");

        lblIAContrasena.setForeground(new java.awt.Color(255, 51, 51));
        lblIAContrasena.setText(" ");

        txtIContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIContrasenaActionPerformed(evt);
            }
        });
        txtIContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIContrasenaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIContrasenaKeyTyped(evt);
            }
        });

        txtITipo.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtIContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnIInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblIContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblIAContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(38, 38, 38))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblINombre, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtINombre, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblIANombre, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(lblIInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(txtITipo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblIInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtITipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(lblINombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtINombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lblIANombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIContraseña)
                .addGap(18, 18, 18)
                .addComponent(txtIContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIAContrasena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIInicio)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIInicioActionPerformed
        Connection con = null;
        try {
            con = getConnection();
            ps = (PreparedStatement) con.prepareStatement("SELECT usuario, contraseña, tipo FROM practicas WHERE usuario = ? and contraseña = ?");
            ps.setString(1, txtINombre.getText());
            ps.setString(2, txtIContrasena.getText());
            
            rs = ps.executeQuery();
            
            if (rs.next()){
                txtINombre.setText(rs.getString("usuario"));
                txtIContrasena.setText(rs.getString("contraseña"));
                txtITipo.setText(rs.getString("tipo"));
            } else {
                JOptionPane.showMessageDialog(null, "El usuario o la contraseña no son validos para el servidor de la conexion de usuarios"
                        + "\nEscriba los datos correctamente o consulte al administrador del sistema");
                limpiar();
                return;
                
            }
        } catch(HeadlessException | SQLException e){
            System.err.println(e);
        }
        
        prueba ventana1 = new prueba();
        ventana1.setDato(txtITipo.getText());
        ventana1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnIInicioActionPerformed

    private void txtINombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtINombreKeyTyped
        //introduce la restriccion ASCII para las cajas de texto
        int key = evt.getKeyChar();
        //usa el codigo ASCII para dar restriccion a la caja de texto
        boolean mayusculas = key >= 65 && key <= 90;
        boolean espacio = key == 32;
        //no admite los demas caracteres de ASCII que no esten en los rangos
        if (!(mayusculas || espacio)){
            evt.consume();
        }
        //restringe el rango de caracteres permitidos
        if (txtINombre.getText().length() >=35) {
            evt.consume();
        }
    }//GEN-LAST:event_txtINombreKeyTyped

    private void txtINombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtINombreActionPerformed

    }//GEN-LAST:event_txtINombreActionPerformed

    private void txtIContrasenaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIContrasenaKeyTyped
        //restringe el rango de caracteres permitidos
        if (txtINombre.getText().length() >=35) {
            evt.consume();
        }
    }//GEN-LAST:event_txtIContrasenaKeyTyped

    private void txtIContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIContrasenaActionPerformed

    }//GEN-LAST:event_txtIContrasenaActionPerformed

    private void txtINombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtINombreKeyReleased
        Validar();
    }//GEN-LAST:event_txtINombreKeyReleased

    private void txtIContrasenaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIContrasenaKeyReleased
        Validar();
    }//GEN-LAST:event_txtIContrasenaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIInicio;
    private javax.swing.JLabel lblIAContrasena;
    private javax.swing.JLabel lblIANombre;
    private javax.swing.JLabel lblIContraseña;
    private javax.swing.JLabel lblIInicio;
    private javax.swing.JLabel lblINombre;
    private javax.swing.JPasswordField txtIContrasena;
    private javax.swing.JTextField txtINombre;
    private javax.swing.JTextField txtITipo;
    // End of variables declaration//GEN-END:variables
}
